services:
  settlr:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - DATABASE_URL=${DATABASE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    container_name: settlr
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    networks:
      - prisma-network
    restart: unless-stopped
    depends_on:
      settlr-migrate:
        condition: service_completed_successfully

  prisma-studio:
    image: node:24.15.0
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env.production
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - prisma-network

  settlr-migrate:
    image: node:24.15.0
    container_name: settlr-migrate
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.production
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - prisma-network
    command: [ "npx", "prisma", "migrate", "deploy" ]
    restart: "no"

networks:
  prisma-network:
    name: prisma-network
