services:
  settlr:
    image: chavda2772/settlr:latest
    container_name: settlr
    environment:
      # Application
      NEXT_PUBLIC_APP_NAME: "Settlr"
      NEXT_PUBLIC_APP_DESCRIPTION: "Settlr for managing personal finance"

      # Better Auth
      BETTER_AUTH_SECRET: "lMD1eol2MrTxIZixGYyjwT0G0DQJ6oLJ"
      BETTER_AUTH_URL: "http://localhost:3000"
      BETTER_AUTH_TRUSTED_ORIGINS: "https://example.com,https://*.example.com"

      # DATABASE
      DATABASE_URL: "postgresql://next_user:next_pass@postgres_db:5432/next_template?schema=public"

      # Email Service
      SMTP_HOST: "mail.example.com"
      SMTP_PORT: 587
      SMTP_USER: "user@example.com"
      SMTP_PASS: "**PASSWORD**"
      SMTP_SECURE: false
      FROM_EMAIL: "user <user@example.com>"

    ports:
      - "3000:3000"
    networks:
      - prisma-network
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:17.4
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: next_template
      POSTGRES_USER: next_user
      POSTGRES_PASSWORD: next_pass
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U next_user -d next_template" ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-studio:
    image: node:24-alpine
    container_name: prisma-studio
    working_dir: /app
    command: npx prisma studio --port 5555 --browser none
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://next_user:next_pass@postgres_db:5432/next_template?schema=public"
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy

networks:
  prisma-network:
    name: prisma-network

volumes:
  postgres_data:
