services:
  postgresql:
    container_name: postgresql
    image: postgres:17.4
    environment:
      - PGID=1000
      - POSTGRES_DB=settlr
      - POSTGRES_PASSWORD=settlr
      - POSTGRES_USER=settlr
      - TZ=Asia/Kolkata
    restart: always
    networks:
      - settlr-network
    volumes:
      - type: bind
        source: /DATA/AppData/postgresql/data
        target: /var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U settlr -d settlr" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prisma-studio: 
    image: node:lts-alpine3.17
    working_dir: /usr/src/app 
    volumes: 
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports: 
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://settlr:settlr@postgresql:5432/settlr
    networks: 
      - settlr-network
    depends_on: 
      postgresql: 
        condition: service_healthy

networks:
  settlr-network:
