services:
  postgres_db:
    image: postgres:17.4
    hostname: postgres_db
    container_name: settlr_postgres_db
    restart: always
    environment:
      POSTGRES_DB: settlr
      POSTGRES_USER: settlr_admin
      POSTGRES_PASSWORD: Settlr@123
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U settlr_admin -d settlr" ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  settlr:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-Settlr}
        - NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION:-Settlr for managing personal finance}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-lMD1eol2MrTxIZixGYyjwT0G0DQJ6oLJ}
        - DATABASE_URL=postgresql://settlr_admin:Settlr@123@postgres_db:5432/settlr?schema=public
        - ADVANCE_PASS_CHECK=${ADVANCE_PASS_CHECK:-true}
    container_name: settlr
    environment:
      # Application
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-Settlr}
      NEXT_PUBLIC_APP_DESCRIPTION: ${NEXT_PUBLIC_APP_DESCRIPTION:-Settlr for managing personal finance}
      ADVANCE_PASS_CHECK: ${ADVANCE_PASS_CHECK:-true}

      # Better Auth
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-lMD1eol2MrTxIZixGYyjwT0G0DQJ6oLJ}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
      BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS:-http://localhost:3000}

      # DATABASE
      DATABASE_URL: "postgresql://settlr_admin:Settlr@123@postgres_db:5432/settlr?schema=public"
    ports:
      - "3000:3000"
    networks:
      - prisma-network
    restart: always
    volumes:
      - settlr_uploads:/app/uploads
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      postgres_db:
        condition: service_healthy

  prisma-studio:
    image: chavda2772/prisma-studio:latest
    container_name: settlr_prisma_studio
    restart: always
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://settlr_admin:Settlr@123@postgres_db:5432/settlr?schema=public"
      STUDIO_PORT: 5555
      STUDIO_HOST: "0.0.0.0"
      STUDIO_BROWSER: "none"
      AUTO_INTROSPECT: ${AUTO_INTROSPECT:-true}
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      settlr:
        condition: service_healthy

networks:
  prisma-network:
    name: prisma-network

volumes:
  postgres_data:
  settlr_uploads:
