services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - DATABASE_URL=${DATABASE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    container_name: app-next
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    networks:
      - prisma-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

  prisma-studio:
    image: node:24-alpine
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - prisma-network

networks:
  prisma-network:
    name: prisma-network
