services:
  postgresql:
    container_name: postgresql
    image: postgres:17.4
    environment:
      - PGID=1000
      - POSTGRES_DB=settlr
      - POSTGRES_PASSWORD=settlr
      - POSTGRES_USER=settlr
      - TZ=Asia/Kolkata
    ports:
      - '5433:5432'
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/postgresql/data
        target: /var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U settlr -d settlr"]
      interval: 10s
      timeout: 5s
      retries: 5

  settlr-web:
    container_name: settlr
    image: settlr:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # Application
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=Settlr
      - NEXT_PUBLIC_APP_DESCRIPTION=Settlr for managing personal finance

      # Better Auth
      - BETTER_AUTH_SECRET=dummy_secret_replace_me_with_32_chars_long
      - BETTER_AUTH_URL=http://settlr.example.com
      - BETTER_AUTH_TRUSTED_ORIGINS=http://settlr.example.com,http://*.settlr.example.com

      # Database
      - DATABASE_URL=postgresql://settlr:settlr@postgresql:5432/settlr

      # Email Service
      - SMTP_HOST=mail.example.com
      - SMTP_PORT=587
      - SMTP_USER=user@example.com
      - SMTP_PASS=password
      - SMTP_SECURE=false
      - FROM_EMAIL=settlr@example.com

      # Google login
      - GOOGLE_CLIENT_ID=dummy
      - GOOGLE_CLIENT_SECRET=dummy

      # Discord
      - DISCORD_CLIENT_ID=dummy
      - DISCORD_CLIENT_SECRET=dummy
    depends_on:
      postgresql:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && node server.js"
    restart: unless-stopped
